#!/bin/bash

# Problem 7

# Train
mkdir -p data/
rm -rf data/p7_*
python train_pg_f18.py LunarLanderContinuous-v2 -ep 1000 --discount 0.99 -n 100 -e 3 -l 2 -s 64 -b 40000 -lr 0.005 -rtg --nn_baseline --exp_name p7_ll_b40000_r0.005

# Plots
p7_files=()
for dir in data/p7_*;
do
	p7_files+=("$dir")
done

mkdir -p plots/
rm -rf plots/p7*
python plot.py ${p7_files[@]} --value AverageReturn --save_name plots/p7.png

