#!/bin/bash

# Problem 4
# Run experiments
mkdir -p data/
rm -rf data/ac_p1_*
python train_ac_f18.py CartPole-v0 -n 100 -b 1000 -e 3 -ntu 1   -ngsptu 1   --exp_name p1_1_1
python train_ac_f18.py CartPole-v0 -n 100 -b 1000 -e 3 -ntu 100 -ngsptu 1   --exp_name p1_100_1
python train_ac_f18.py CartPole-v0 -n 100 -b 1000 -e 3 -ntu 1   -ngsptu 100 --exp_name p1_1_100
python train_ac_f18.py CartPole-v0 -n 100 -b 5000 -e 3 -ntu 10  -ngsptu 10  --exp_name p1_10_10

# Plot
ac_p1_files=()
for dir in data/ac_p1_*;
do
	ac_p1_files+=("$dir")
done

python plot.py ${ac_p1_files[@]} --value AverageReturn
