#!/bin/bash

mkdir -p data/
rm -rf data/ac_p2_b_*

python train_ac_f18.py HalfCheetah-v2 -ep 150 --discount 0.90 -n 100 -e 3 -l 2 -s 32 -b 30000 -lr 0.02 --exp_name p2_b_10_10 -ntu 10 -ngsptu 10

# Plot
f=()
for dir in data/ac_p2_b_*;
do
        f+=("$dir")
done

python plot.py ${f[@]} --value AverageReturn

